[package]
name = "kybe-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
futures = "0.3.31"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1.48", features = ["full"] }
toml = "0.9.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1.0.147"
meval = "0.2.0"
sqlx = { version="0.8.6", features = ["runtime-tokio", "tls-rustls", "postgres", "uuid", "chrono"] }
poise = { git = "https://github.com/serenity-rs/poise", branch = "current"}
chrono = "0.4.42"
log = "0.4.29"
tracing-appender = "0.2.4"
uuid = { version = "1.19.0", features = ["v7"] }
axum = { version = "0.8.8", features = ["macros"] }
anyhow = "1.0.100"
argon2 = "0.5.3"
