[package]
name = "kybe-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
futures = "0.3.31"
poise = "0.6.1"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.17"
tokio = { version = "1.48", features = ["full"] }
toml = "0.9.10"
tracing = "0.1"
tracing-subscriber = "0.3"
webhook = { version = "2.1.2" }
