[notification.log]
enabled = true

[notification.gotify]
enabled = false
url = "https://gotify.kybe.xyz/message?token=<token>"

[notification.discord]
enabled = false
url = "https://discord.com/api/webhooks/.../..."
