services:
  kybe-backend:
    image: reg.kybe.xyz/kybe-pub/kybe-backend:latest
    container_name: kybe-backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./backend/config.toml:/opt/backend/config.toml
      - ./backend/logs:/opt/backend/logs
    environment:
      - KYBE_DATABASE_POSTGRES_URL=postgres://kybe:kybe@postgres:5432/kybe_db
    depends_on:
      - postgres

  postgres:
    image: postgres:18.1-alpine
    container_name: kybe-postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: kybe
      POSTGRES_PASSWORD: kybe
      POSTGRES_DB: kybe_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
