name: Build and Deploy
on:
  push:
    branches:
      - main

env:
  IMAGE: reg.kybe.xyz/kybe-pub/kybe-backend
  REGISTRY_URL: reg.kybe.xyz
  TAG: ${{ github.sha }}

jobs:
  deploy-backend:
    name: Build, Push & Deploy Backend
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v5

      - name: Log in to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ env.TAG }}
            ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.RUNNER_SSH_KEY }}
          script: |
            echo "${{ secrets.REGISTRY_PASS }}" | docker login ${{ env.REGISTRY_URL }} -u "${{ vars.REGISTRY_USER }}" --password-stdin
            cd /opt/backend
            docker compose pull
            docker compose up -d --force-recreate --remove-orphans
          envs: REGISTRY_URL,REGISTRY_USER